feat(person-listitem): plain property
equinor/fusion-web-components pull request #1331
Opened 2024-01-31 08:32 UTC by AndrejNikolicEq

### Person
## Person ListItem

**ListItem - new feature**: `plain` property added for removing border and border-radius from list item component

2024-01-31 08:43 UTC, odinr requested changes
less is more

the frame is just from re-factor of previous code, the frame should not be here, the parent should add this frame _if required_

just make the version major and remove border

btw, classes in WC do not require BEM, since their styling and classes are contained within the shadow DOM. _the bem impl. is just a misunderstanding from previous dev, since the base classes from material design (which uses the plain js/css from root)_

2024-01-31 08:47 UTC, AndrejNikolicEq commented
@odinr Was thinking of quick fix, until we get the new design.
But, since we are doing this, gonna swap whole css with styled-components and tokens from EDS

2024-02-09 09:58 UTC, eikeland commented on .changeset/odd-camels-know.md
> +'@equinor/fusion-wc-person': minor
Make this a major version bump.

2024-03-19 14:30 UTC, asbjornhaland commented
What is the status of this? should it still be open?

2024-04-03 06:22 UTC, AndrejNikolicEq commented
> What is the status of this? should it still be open?

We can leave it open for now, need to check if we still want it

2024-08-23 06:35 UTC, AndrejNikolicEq commented
We do not need it any more, we have new component that covers it

2024-08-23 06:35 UTC, closed without merging