Feat/searchabledropdown/autofocus
equinor/fusion-web-components pull request #457
Opened 2023-01-17 09:02 UTC by eikeland

Adding ``autofocus`` property to ``fusion-wc-searchable-dropdown`` so consumer can put focus on the child component ``fwc-textinput`` when  component is connected to DOM.

Also exposing ``textInput`` from the controller so consumer can access the ``fwc-textinput`` child component element in the ShadowDOM.

2023-01-18 10:04 UTC, odinr requested changes
have a look at [delegate focus](https://lit.dev/docs/components/shadow-dom/#setting-shadowrootoptions)

2023-01-18 10:04 UTC, odinr commented on packages/searchable-dropdown/src/provider/controller.ts
> +      this.textInput = this.textInput ?? this.#host.renderRoot.querySelector('fwc-textinput');
@see [query](https://lit.dev/docs/v1/api/lit-element/decorators/#query)

2023-01-18 15:06 UTC, eikeland commented
still keeping the property for autofocus since it is easier to implement for consumners then a focus hook.
But they can now trigger focus on the parent components since delegateFocus is true.

2023-01-19 11:26 UTC, odinr approved these changes

2023-01-19 11:45 UTC, merged